# Site settings
title: Niclas Hammar UDM 2015
email: nh222fv@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio during my studies and this site is where i will publish my finishied projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://hammarpojken.github.io/ # the base hostname & protocol for your site
github_username:  hammarpojken

# Build settings
markdown: kramdown
